### ISSUE TITLE
More Ghost Types

### ISSUE THREAD

**Issue by cdsupina** [UMN-Kernel-Object/rust-pacman#2]
Currently we have one ghost in the game, the red ghost. Let's add 8 more ghosts to the game that all perform different attack behaviors. I have enumerated ideas for the behaviors in the list below, but feel free to be creative if you find more interesting ideas.

- [x] Red: Directly pursues the player #1 
- [ ] Orange: Moves a random direction every couple of seconds
- [ ] Green: Alternates moving left and right
- [x] Pink: Alternates moving up and down #5 
- [ ] Purple: Moves in a circle
- [x] Brown: Moves away from player #6 
- [ ] Cyan: Directly pursues the player, only if the player is within a range
- [ ] Blue: Alternates between moving up, down, left, and right
- [ ] Grey: Patrol the outer perimeter of the window
